---
galaxy_info:
  role_name: nginx_proxy
  author: Corey Ducre
  description: nginx_proxy role for Charlotte_2026 configuration management
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "9"
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags: []

dependencies: []
